### PR TITLE
Add DIC

### PR DESCRIPTION
**Pull request by itsdfish**
Hi Rob,

I added DIC to your package. I also removed `logsumexp` since that is available in `StatsFuns`.

### CODE REVIEW

**Comment by itsdfish** [comment]
I was also thinking that other packages, such as MCMCChains, could add their own methods to interface with dic, psiloo etc. For example, MCMCChains could use:

```
function dic(chain::Chains)
    lps = get(chain, :lp).lp[:] |> Array
    return dic(lps)
end
```

**Comment by goedman** [comment]
HI Chris, thanks for the PR. Yes, I had switched to the use of logsumexp in StatsFuns. I'll check the StatisticalRethinking (SR) layer additions to PSIS such as plot_models() and compare(). And after I run a few more checks on trankplot() (a newer suggestion to check chains) I'll update both packages.

Slowly I'm getting the hang how to consistently make SR mcmc package independent. For PSIS this is fairly simple as we pass in a logic matrix. Haven't tested yet if your above `lps` works in psisloo().

**Comment by itsdfish** [comment]
Sounds good. In order to use PSIS with MCMCChains, I think there needs to be an intermediate step where the pointwise log likelihoods are computed for each MCMC sample. I agree with you that such methods should be in MCMCChains, and the API here should be as generic as possible.

**Comment by goedman** [comment]
Yes, you're right, `lps` in your example is not the pointwise loglik for each observation given the samples.

**Pull request merged**
